# Generated by Django 5.1.5 on 2025-01-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
