# Generated by Django 5.1.5 on 2025-01-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RR", "0002_alter_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("volume", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(max_length=50)),
                ("exchange_books", models.TextField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("contact", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("image", models.ImageField(upload_to="book_images/")),
            ],
        ),
    ]
