# Generated by Django 5.1.5 on 2025-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RR", "0003_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadAndEarnBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("volume", models.CharField(blank=True, max_length=100, null=True)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="read_and_earn_books/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
