# Generated by Django 5.1.5 on 2025-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RR', '0004_readandearnbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='readandearnbook',
            name='date_of_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
