# Generated by Django 5.1.5 on 2025-01-23 04:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RR", "0005_readandearnbook_date_of_submission"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=100)),
                ("volume", models.CharField(blank=True, max_length=100, null=True)),
                ("availability", models.CharField(max_length=200)),
                ("review", models.TextField()),
                ("pros", models.TextField()),
                ("cons", models.TextField()),
                ("reviewed_by", models.CharField(max_length=100)),
                ("review_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="book_reviews/"),
                ),
            ],
        ),
    ]
