# Generated by Django 5.1.5 on 2025-01-23 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RR", "0006_bookreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("comment", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "book_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="RR.bookreview",
                    ),
                ),
            ],
        ),
    ]
