# Generated by Django 5.1.5 on 2025-01-23 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RR", "0008_blog_remove_comment_book_review_comment_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="RR.blog",
            ),
        ),
    ]
