# Generated by Django 5.1.5 on 2025-01-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RR", "0009_alter_comment_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=200)),
                ("book_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("book_link", models.URLField()),
                (
                    "package",
                    models.CharField(
                        choices=[
                            ("Diamond", "Diamond"),
                            ("Platinum", "Platinum"),
                            ("Gold", "Gold"),
                        ],
                        max_length=10,
                    ),
                ),
                ("book_image", models.ImageField(upload_to="package_images/")),
                ("book_pdf", models.FileField(upload_to="package_pdfs/")),
            ],
        ),
    ]
